version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3307:3306
  app:
    build: ./Server
    restart: always
    ports:
      - 80:80
    depends_on:
      - database